### ISSUE TITLE
Basic example repo

### ISSUE THREAD

**Issue by atomiks** [NeekSandhu/codemirror-textmate#1]
Would it be possible create a basic example repo using `parcel-bundler` + single index.html page with an editor loading the Atom One Dark theme?

**Comment by zikaari** [comment]
Makes sense. Will set it up by tomorrow ☺️

**Comment by zikaari** [comment]
Done!!

Unfortunately, it's with webpack, not parcel.

`codemirror-textmate` depends on `onigasm` which needs `onigasm.wasm` file loaded either as `ArrayBuffer` or as URL. Parcel resolves `.wasm` files literally through its built-in mechanisms which prevents `onigasm` from working.

**Comment by atomiks** [comment]
Thank you very much for the example! For some reason, I couldn't just drop in [my theme](https://github.com/atomiks/moonlight-vscode-theme/tree/master/themes) to the OneDark example because many of the colors were incorrect. From investigating it seems like it didn't interpet nested scopes, like `meta.class-method.js entity.name.function.js` (note the space). 

Edit: However, I'm able to convert it over with some edits so it's fine :-)

Is JSX syntax highlighting also possible?

**Comment by zikaari** [comment]
JSX syntax highlighting is possible through [`JavaScriptReact.tmLanguage.json`](https://github.com/NeekSandhu/monaco-textmate-languages/blob/master/grammars/javascript/JavaScriptReact.tmLanguage.json) and [`TypeScript.tmLanguage.json`](https://github.com/NeekSandhu/monaco-textmate-languages/blob/master/grammars/typescript/TypeScriptReact.tmLanguage.json)
